root_path: 
method_name: 

data_set: forget01
model_path:  
tokenizer_path: 
model_family: phi

unlearn: False
do_peft: False

#dataset path for each of the 4 datasets to be evaluated
data_path: [locuslab/TOFU, locuslab/TOFU, locuslab/TOFU, locuslab/TOFU]
split: ${data_set}_perturbed
split_list:
  - retain_perturbed
  - real_authors_perturbed
  - world_facts_perturbed
  - ${split}

save_dir: ${root_path}/eval_results/${method_name}_${model_family}_${split}

question_key: [question, question, question, question]
answer_key: [answer, answer, answer, answer]

base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]

generation:
  max_length: 200
  max_new_tokens: null

save_generated_text: true

ds_size: 300

overwrite: true
use_pretrained: false

batch_size: 12
reinitialize_weights: false

retain_result: tofu/data/ft_epoch5_lr1e-05_llama2-7b_retain99_wd0/eval_results/ds_size300/eval_log_aggregated.json
ckpt_result: ${save_dir}/eval_log_aggregated.json
save_file: ${save_dir}/test_result.csv
submitted_by: Carol